//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotoStreet_1._0_ControlStreet
{
    using System;
    using System.Collections.Generic;
    
    public partial class errors
    {
        public int bejegyzes_Id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string name { get; set; }
        public string error { get; set; }
        public string id { get; set; }
    }
}
