//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotoStreet_1._0_ControlStreet
{
    using System;
    using System.Collections.Generic;
    
    public partial class police
    {
        public int police_office_id { get; set; }
        public string name { get; set; }
    }
}
