//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotoStreet_1._0_ControlStreet
{
    using System;
    using System.Collections.Generic;
    
    public partial class pworks
    {
        public int Id { get; set; }
        public Nullable<int> userid { get; set; }
        public string work { get; set; }
        public Nullable<System.DateTime> login_date { get; set; }
        public Nullable<int> logintimehour { get; set; }
        public Nullable<int> loginexithour { get; set; }
    }
}
