//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotoStreet_1._0_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> adoszam { get; set; }
        public string Company_manager { get; set; }
        public string password { get; set; }
    }
}
