//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotoStreet_1._0_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emlpoye_Certificate
    {
        public int Id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> Companyid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
