//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotoStreet_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authenticated_user
    {
        public int userid { get; set; }
        public string Mother_name { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public string ICN { get; set; }
    
        public virtual user user { get; set; }
    }
}
