//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotoStreet_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public int userid { get; set; }
        public string city1 { get; set; }
        public int zip { get; set; }
        public string street { get; set; }
        public string place { get; set; }
        public string housenumber { get; set; }
    
        public virtual user user { get; set; }
    }
}
