//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotoStreet_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class gotoStreet
    {
        public int Id { get; set; }
        public int userid { get; set; }
        public Nullable<System.DateTime> go_date { get; set; }
        public Nullable<System.DateTime> record_date { get; set; }
        public string cel { get; set; }
        public string status { get; set; }
        public string mode { get; set; }
    
        public virtual user user { get; set; }
    }
}
