//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotoStreet_1._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gotoStreetEntities1 : DbContext
    {
        public gotoStreetEntities1()
            : base("name=gotoStreetEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<gotoStreet> gotoStreet { get; set; }
        public virtual DbSet<police> police { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<Authenticated_user> Authenticated_user { get; set; }
    }
}
